React HW_3 Тимонина Мария
timmmariya/react-basics pull request #1
Opened 2020-02-19 14:52 UTC by timmmariya

2020-02-19 14:56 UTC, sizovk commented on src/App.js
> +    <div>{descr}</div>
description

2020-02-29 18:25 UTC, ValeryStatinov requested changes
в целом хорошо. после исправления замечаний будет отл(8)

как исправлять?
внести изменения в код, закоммитить и запушить изменения в эту ветку. после этого перезапросить мое ревью

<img width="266" alt="Снимок экрана 2020-02-29 в 20 30 06" src="https://user-images.githubusercontent.com/35629771/75613011-f632a880-5b39-11ea-976e-71ca060d7b36.png">

2020-02-29 18:25 UTC, ValeryStatinov commented on src/App.js
> +    this.setState(state => ({ name: newValue  }));
если для формирования нового стейта не нужно текущее состояние, то в `setState` можно просто передавать объект. в данном случае можно написать так:
```
this.setState({ name: newValue });
```

2020-02-29 18:25 UTC, ValeryStatinov commented on src/App.js
> +    this.setState(state => (state.tasks.push(taski)));
мутация стейта!!!
`state => (state.tasks.push(taski))` эта функция должна вернуть НОВЫЙ объект.

почему это опасно? разберемся, что тут происходит
* вызывается ф-ия `PushNewTask`
* мутируется стейт
* так как был вызван метод `setState`, то запустится ререндер
* компонент перерендерится с мутированным стейтом, выглядит все как и хотелось

что может произойти:
* вызывается ф-ия `PushNewTask`
* завершается асинхронный запрос на backend за какими-либо данными, в стейт кладется НОВЫЙ объект
* мутируется СТАРЫЙ стейт в `PushNewTask`
* так как был вызван метод `setState`, то запустится ререндер
* компонент перерендерится с НОВЫМ объектом стейта, который был туда положен во 2ом пункте; без таски, которую хотелось добавить по нажатию на кнопку

итог: новая таска, которая была добавлена в СТАРЫЙ стейт путем мутация потеряна

что нужно делать? каждый раз возвращать новый объект!
```javascript
this.setState(state => {
  const newState = { ...state }; // таким образом мы создали копию
  // теперь можно мутировать newState
  newState.tasks.push(newTask);
  return newState;
});
```

2020-02-29 18:25 UTC, ValeryStatinov commented on src/App.js
> +    this.setState(state => this.state.tasks.sort(this.byField('name')));
мутация стейта

2020-02-29 18:25 UTC, ValeryStatinov commented on src/App.js
> +    this.setState(state => this.state.tasks.sort(this.byField('prior')));
мутация стейта

2020-03-03 05:41 UTC, ValeryStatinov approved these changes
сейчас засчитываю задание, хотя присутствуют мутации, так как сам написал неверное решение в прошлый раз. Однако прошу это поправить в следующем дз

2020-03-03 05:41 UTC, ValeryStatinov commented on src/App.js
> +    this.setState(state => {
все еще происходит мутация данных:)
прошу прощения, ввел в заблуждение своим прошлым комментарием.

при `const newState = { ...state }` происходит shallow, то есть неглубокое копирование. это значит, что
```javascript
newState === state // false

// однако
newState.tasks === state.tasks // true
```
нужно внутри `newState` так же создать копию `tasks`:
```javascript
const newState = { ...state, tasks: [ ...state.tasks ] };
// теперь можно делать с newState.tasks что угодно
newState.tasks.push(newEl);
return newState;
```

2020-03-03 05:41 UTC, ValeryStatinov commented on src/App.js
> +      newState.tasks.sort(this.byField('name'));
мутация

2020-03-03 05:41 UTC, ValeryStatinov commented on src/App.js
> +      newState.tasks.sort(this.byField('prior'));
мутация

2020-03-03 05:42 UTC, merged